version: '3.8'
services:
  almoapi:
    # Uncomment this to build a docker image from source
    build:
      context: .
      dockerfile: Dockerfile

    # Comment this to build a docker image from source
    #image: ghcr.io/almoapi/almoapi:latest
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - NAME=ALMoAPI
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./models:/app/models  # Adjust this path if needed
      - ./loras:/app/loras  # Adjust this path if needed
      - ./config.yml:/app/config.yml  # change if necessary
      - ./api_tokens.yml:/app/api_tokens.yml  # change if necessary
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
